<?php

/*
 *  ACF Pro Fields for UAMS-2016
 */


add_filter( 'rwmb_meta_boxes', 'uams_people_register_meta_boxes' );

function uams_people_register_meta_boxes( $meta_boxes ) {

    $meta_boxes[] = array (
      'id' => 'locations',
      'title' => 'Location Information',
      'post_types' =>   array (
         'locations',
      ),
      'context' => 'normal',
      'priority' => 'high',
      'autosave' => true,
      'fields' =>   array (
         
        array (
          'id' => 'location_abbreviation',
          'type' => 'text',
          'name' => 'Abbreviation',
        ),
         
        array (
          'id' => 'location_address_1',
          'type' => 'text',
          'name' => 'Address',
        ),
         
        array (
          'id' => 'location_address_2',
          'type' => 'text',
          'name' => 'Address (2)',
        ),
         
        array (
          'id' => 'location_city',
          'type' => 'text',
          'name' => 'City',
        ),
         
        array (
          'id' => 'location_state',
          'name' => 'State',
          'type' => 'select',
          'placeholder' => 'Select an Item',
          'options' =>       array (
            'AR' => 'Arkansas',
            'AL' => 'Alabama',
          ),
          'std' =>       array (
             'AR',
          ),
        ),
         
        array (
          'id' => 'location_zip',
          'type' => 'text',
          'name' => 'Zip',
          'placeholder' => '72205',
          'size' => '30',
        ),
         
        array (
          'id' => 'location_map',
          'type' => 'map',
          'name' => 'Map',
          'std' => '34.7492719,-92.3198281,14',
          'address_field' => 'location_address_1,location_city,location_state,location_zip',
        ),
         
        array (
          'id' => 'location_phone',
          'type' => 'text',
          'name' => 'Phone',
        ),
         
        array (
          'id' => 'location_fax',
          'type' => 'text',
          'name' => 'Fax',
        ),
         
        array (
          'id' => 'location_email',
          'name' => 'Email',
          'type' => 'email',
        ),
         
        array (
          'id' => 'location_web_name',
          'type' => 'text',
          'name' => 'Website Name',
        ),
         
        array (
          'id' => 'location_url',
          'type' => 'url',
          'name' => 'URL',
        ),
      ),
      'validation' => array(
		    'rules'  => array(
		        'location_address_1' => array(
		            'required'  => true,
		        ),
		        'location_city' => array(
		            'required'  => true,
		        ),
		        'location_state' => array(
		            'required'  => true,
		        ),
		        'location_zip' => array(
		            'required'  => true,
		            'zipcodeUS' => true,
		            'maxlength' => 10,
          			'minlength' => 5,
		        ),
		        'location_map' => array(
		            'required'  => true,
		        ),
		        'location_phone' => array(
		            'required'  => true,
		            'phoneUS' => true,
		        ),
		    ),
		    // Optional override of default error messages
		    // 'messages' => array(
		    //     'field_id' => array(
		    //         'required'  => 'Password is required',
		    //         'minlength' => 'Password must be at least 7 characters',
		    //     ),
		    // )
		),
    );

    //return $meta_boxes;

    $meta_boxes[] = array (
      'id' => 'people',
      'title' => 'People',
      'post_types' =>   array (
         'people',
      ),
      'context' => 'normal',
      'priority' => 'high',
      'autosave' => true,
      'tab_style' => 'default',
      'tab_wrapper' => true,
      'tabs' =>   array (
	        'tab_details' =>     array (
	          'label' => 'Details',
	          'icon' => 'dashicons-admin-users',
	        ),
	        'tab_clin_profile' =>     array (
	          'label' => 'Clinical Profile',
	          'icon' => 'dashicons-id-alt',
	        ),
	        'tab_clin_details' =>     array (
	          'label' => 'Clinical Details',
	          'icon' => 'dashicons-forms',
	        ),
	        'tab_academic' =>     array (
	          'label' => 'Academic Profile',
	          'icon' => 'dashicons-edit',
	        ),
	        'tab_edu' =>     array (
	          'label' => 'Education',
	          'icon' => 'dashicons-book-alt',
	        ),
	        'tab_research' =>     array (
	          'label' => 'Research',
	          'icon' => 'dashicons-clipboard',
	        ),
	        'tab_extra' =>     array (
	          'label' => 'Extra',
	          'icon' => 'dashicons-awards',
	        ),
      ),

      'fields' =>   array (
         
        array (
	        'id' => 'profile_type',
	        'type' => 'taxonomy',
	        'name' => 'Profile Type',
	        'taxonomy' => 'profile_type',
	        'field_type' => 'checkbox_list',
        ),
         
        array (
          	'id' => 'person_first_name',
          	'type' => 'text',
          	'name' => 'First Name',
          	'tab' => 'tab_details',
        ),
         
        array (
          	'id' => 'person_middle_name',
          	'type' => 'text',
          	'name' => 'Middle Name',
          	'tab' => 'tab_details',
        ),
         
        array (
          'id' => 'person_last_name',
          'type' => 'text',
          'name' => 'Last Name',
          'tab' => 'tab_details',
        ),
         
        array (
          'id' => 'person_degree',
          'type' => 'text',
          'name' => 'Degree',
          'tab' => 'tab_details',
        ),
         
        array (
          'id' => 'person_photo',
          'type' => 'image',
          'name' => 'Photo',
          'max_file_uploads' => 4,
          'tab' => 'tab_details',
        ),
         
        array (
          'id' => 'physician_title',
          'type' => 'text',
          'name' => 'Title',
          'tab' => 'tab_clin_profile',
        ),
         
        array (
          'id' => 'physician_clinical_bio',
          'name' => 'Clinical Bio',
          'type' => 'wysiwyg',
          'tab' => 'tab_clin_profile',
        ),
         
        array (
          'id' => 'physician_short_clinical_bio',
          'type' => 'textarea',
          'name' => 'Short Bio',
          'tab' => 'tab_clin_profile',
        ),
         
        array (
          'id' => 'physician_gender',
          'name' => 'Gender',
          'type' => 'radio',
          'tab' => 'tab_clin_profile',
        ),
         
        array (
          'id' => 'physician_youtube_link',
          'type' => 'url',
          'name' => 'Youtube Link',
          'tab' => 'tab_clin_profile',
        ),
         
        array (
          'id' => 'physician_languages',
          'name' => 'Language(s)',
          'type' => 'select',
          'placeholder' => 'Select an Item',
        ),
         
        array (
          'id' => 'physician_locations',
          'type' => 'post',
          'name' => 'Locations',
          'post_type' => 'locations',
          'field_type' => 'select_advanced',
          'tab' => 'tab_clin_profile',
        ),
         
        array (
          'id' => 'physician_affiliation',
          'name' => 'Affiliation',
          'type' => 'checkbox',
          'desc' => 'Default Description',
          'tab' => 'tab_clin_profile',
        ),
         
        array (
          'id' => 'clinical_info',
          'type' => 'heading',
          'name' => 'Clinical Info',
          'tab' => 'tab_clin_details',
        ),
         
        array (
          'id' => 'physician_appointment_link',
          'type' => 'url',
          'name' => 'Appointment Link',
          'tab' => 'tab_clin_details',
        ),
         
        array (
          'id' => 'physician_primary_care',
          'name' => 'Primary Care',
          'type' => 'checkbox',
          'desc' => 'Default Description',
          'tab' => 'tab_clin_details',
        ),
         
        array (
          'id' => 'physician_refferal_required',
          'name' => 'Referral Required',
          'type' => 'checkbox',
          'desc' => 'Default Description',
        ),
         
        array (
          'id' => 'physician_accepting_patients',
          'name' => 'Accepting New Patients',
          'type' => 'checkbox',
          'desc' => 'Default Description',
          'tab' => 'tab_clin_details',
        ),
         
        array (
          'id' => 'physician_second_opinion',
          'name' => 'Provides Second Opinion',
          'type' => 'checkbox',
          'desc' => 'Default Description',
          'tab' => 'tab_clin_details',
        ),
         
        array (
          'id' => 'physician_patient_types',
          'type' => 'taxonomy',
          'name' => 'Patient Types',
          'taxonomy' => 'patient_type',
          'field_type' => 'select',
          'tab' => 'tab_clin_details',
        ),
         
        array (
          'id' => 'medical_specialties',
          'type' => 'taxonomy',
          'name' => 'Medical Specialties',
          'taxonomy' => 'specialties',
          'field_type' => 'select',
          'tab' => 'tab_clin_details',
        ),
         
        array (
          'id' => 'physician_conditions',
          'type' => 'taxonomy',
          'name' => 'Conditions Treated',
          'taxonomy' => 'condition',
          'field_type' => 'select_advanced',
          'tab' => 'tab_clin_details',
        ),
         
        array (
          'id' => 'medical_procedures',
          'type' => 'taxonomy',
          'name' => 'Medical Procedures',
          'taxonomy' => 'medical_procedures',
          'field_type' => 'select',
          'tab' => 'tab_clin_details',
        ),
         
        array (
          'id' => 'medical_terms',
          'type' => 'taxonomy',
          'name' => 'Medical Terms (Tags)',
          'taxonomy' => 'medical-terms',
          'field_type' => 'select_advanced',
          'tab' => 'tab_clin_details',
        ),
         
        array (
          'id' => 'physician_pid',
          'type' => 'text',
          'name' => 'PID',
          'tab' => 'tab_clin_details',
        ),
         
        array (
          'id' => 'physician_npi',
          'type' => 'text',
          'name' => 'NPI',
          'tab' => 'tab_clin_details',
        ),
         
        array (
          'id' => 'profile_info',
          'type' => 'heading',
          'desc' => 'Information',
          'name' => 'Profile Information',
          'tab' => 'tab_academic',
        ),
         
        array (
          'id' => 'person_academic_title',
          'type' => 'text',
          'name' => 'Academic Title',
          'tab' => 'tab_academic',
        ),
         
        array (
          'id' => 'person_academic_college',
          'type' => 'taxonomy',
          'name' => 'College Affiliation',
          'taxonomy' => 'category',
          'field_type' => 'select',
          'tab' => 'tab_academic',
        ),
         
        array (
          'id' => 'person_academic_position',
          'type' => 'taxonomy',
          'name' => 'Position',
          'taxonomy' => 'category',
          'field_type' => 'select',
          'tab' => 'tab_academic',
        ),
         
        array (
          'id' => 'person_academic_bio',
          'name' => 'Academic Bio',
          'type' => 'wysiwyg',
          'tab' => 'tab_academic',
        ),
         
        array (
          'id' => 'person_academic_short_bio',
          'type' => 'textarea',
          'name' => 'Short Academic Bio',
          'tab' => 'tab_academic',
        ),
         
        array (
          'id' => 'person_academic_office',
          'type' => 'textarea',
          'name' => 'Office Location',
          'tab' => 'tab_academic',
        ),
         
        array (
          'id' => 'person_academic_map',
          'name' => 'Map',
          'type' => 'select',
          'placeholder' => 'Select an Item',
          'tab' => 'tab_academic',
        ),

        array(
          	'id'     => 'person_contact_infomation',
          	'type'   => 'group',
          	'tab' => 'tab_academic',
	      	'clone'  => true,
	      	'sort_clone' => true,
	      	'fields' => array(
	            array(
	                'name' => 'Type',
	                'id'   => 'office_contact_type',
	                'type' => 'select',
	                'options' => array(
	                	'phone' => 'Phone',
						'fax' => 'Fax',
						'mobile' => 'Mobile',
						'email' => 'Email',
						'sms' => 'Text/SMS',
	                ),
	            ),
	            array(
	                'name' => 'Value',
	                'id'   => 'office_contact_value',
	                'type' => 'text',
	            ),
        	),
        ),

        array(
          	'id'     => 'person_academic_appointment',
          	'type'   => 'group',
          	'tab' => 'tab_edu',
	      	'clone'  => true,
	      	'sort_clone' => true,
	      	'fields' => array(
	            array(
	                'name' => 'Academic Title',
	                'id'   => 'academic_title',
	                'type' => 'text',
	            ),
	            array(
	                'name' => 'Department',
	                'id'   => 'academic_department',
	                'type' => 'select',
	                'options' => array(
	                	'anesthesiology' => 'Anesthesiology',
						'audiology' => 'Audiology',
						'breastsurgicaloncology' => 'Breast Surgical Oncology',
						'cardiology' => 'Cardiology',
						'clinicalnutrition' => 'Clinical Nutrition',
						'collegeofmedicine' => 'College of Medicine',
						'collegeofpublichealth' => 'College of Public Health',
						'departmentofepidemiology' => 'Department of Epidemiology',
						'departmentofmedicine-divisionofendocrinology' => 'Department of Medicine, Division of Endocrinology',
						'departmentofpediatrics' => 'Department of Pediatrics',
						'departmentofpediatrics-developmentalbehavioral' => 'Department Of Pediatrics/Developmental Behavioral',
						'dermatology' => 'Dermatology',
						'emergency&trauma' => 'Emergency & Trauma',
						'endocrinology-metabolism' => 'Endocrinology/Metabolism',
						'epidemiology' => 'Epidemiology',
						'epidemiology-collegeofpublichealth' => 'Epidemiology, College of Public Health',
						'familyandpreventivemedicine' => 'Family and Preventive Medicine',
						'gastroenterology' => 'Gastroenterology',
						'generalinternalmedicine' => 'General Internal Medicine',
						'genetics' => 'Genetics',
						'geriatrics' => 'Geriatrics',
						'handtherapy' => 'Hand Therapy',
						'hematologyandoncology' => 'Hematology and Oncology',
						'infectiousdiseases' => 'Infectious Diseases',
						'internalmedicine' => 'Internal Medicine',
						'interventionalpainclinic' => 'Interventional Pain Clinic',
						'interventionalradiology' => 'Interventional Radiology',
						'medicalhumanities' => 'Medical Humanities',
						'myeloma&transplantation' => 'Myeloma & Transplantation',
						'myelomainstitute' => 'Myeloma Institute',
						'nephrology' => 'Nephrology',
						'neuro-oncology' => 'Neuro-Oncology',
						'neurobiologyanddevelopmentalscience' => 'Neurobiology and Developmental Science',
						'neurology' => 'Neurology',
						'neurosurgery' => 'Neurosurgery',
						'obstetricsandgynecology' => 'Obstetrics And Gynecology',
						'occupationaltherapy-handtherapy' => 'Occupational Therapy - Hand Therapy',
						'ophthalmology' => 'Ophthalmology',
						'orthopaedicsurgery' => 'Orthopaedic Surgery',
						'otolaryngology-headandnecksurgery' => 'Otolaryngology - Head and Neck Surgery',
						'outpatienttherapy' => 'Outpatient Therapy',
						'pathology' => 'Pathology',
						'pediatric-cardiac-anesthesiology' => 'Pediatric Cardiac Anesthesiology',
						'pediatrics-adolescentmedicine' => 'Pediatrics - Adolescent Medicine',
						'pediatrics-all' => 'Pediatrics - All',
						'pediatrics-cardiology' => 'Pediatrics - Cardiology',
						'pediatrics-childrenatrisk' => 'Pediatrics - Children at Risk',
						'pediatrics-communitypediatrics' => 'Pediatrics - Community Pediatrics',
						'pediatrics-dermatology' => 'Pediatrics - Dermatology',
						'pediatrics-developmentalpediatrics/physmed' => 'Pediatrics - Developmental Pediatrics/Phys Med',
						'pediatrics-endocrinologyanddiabetes' => 'Pediatrics - Endocrinology and Diabetes',
						'pediatrics-generalpediatrics' => 'Pediatrics - General Pediatrics',
						'pediatrics-genetics' => 'Pediatrics - Genetics',
						'pediatrics-neonatalandperinatalmedicine' => 'Pediatrics - Neonatal and Perinatal Medicine',
						'pediatrics-neonatology' => 'Pediatrics - Neonatology',
						'pediatrics-orthopaedicsurgery' => 'Pediatrics - Orthopaedic Surgery',
						'pediatrics-pediatricallergyandimmunology' => 'Pediatrics - Pediatric Allergy and Immunology',
						'pediatrics-pediatriccardiology' => 'Pediatrics - Pediatric Cardiology',
						'pediatrics-pediatriccriticalcaremedicine' => 'Pediatrics - Pediatric Critical Care Medicine',
						'pediatrics-pediatricemergencymedicine' => 'Pediatrics - Pediatric Emergency Medicine',
						'pediatrics-pediatricendocrinology' => 'Pediatrics - Pediatric Endocrinology',
						'pediatrics-pediatricgastroenterology' => 'Pediatrics - Pediatric Gastroenterology',
						'pediatrics-pediatricgynecology' => 'Pediatrics - Pediatric Gynecology',
						'pediatrics-pediatrichematology/oncology' => 'Pediatrics - Pediatric Hematology/Oncology',
						'pediatrics-pediatricinfectiousdisease' => 'Pediatrics - Pediatric Infectious Disease',
						'pediatrics-pediatricnephrology' => 'Pediatrics - Pediatric Nephrology',
						'pediatrics-pediatricneurology' => 'Pediatrics - Pediatric Neurology',
						'pediatrics-pediatricrheumatology' => 'Pediatrics - Pediatric Rheumatology',
						'pediatrics-pediatricurology' => 'Pediatrics - Pediatric Urology',
						'pediatrics-pharmacology/toxicology' => 'Pediatrics - Pharmacology/Toxicology',
						'pediatrics-psychology' => 'Pediatrics - Psychology',
						'pediatrics-pulmonary' => 'Pediatrics - Pulmonary',
						'pediatrics-radiology' => 'Pediatrics - Radiology',
						'pediatrics-schmieding' => 'Pediatrics - Schmieding Developmental Center, Lowell, AR',
						'physical-medicine-rehabilitation' => 'Physical Medicine and Rehabilitation',
						'psychiatry' => 'Psychiatry',
						'pulmonary-critical-care-medicine' => 'Pulmonary and Critical Care Medicine',
						'radiationoncology' => 'Radiation Oncology',
						'radiology' => 'Radiology',
						'rheumatology' => 'Rheumatology',
						'surgery-all' => 'Surgery - All',
						'surgery-burnservice' => 'Surgery - Burn Service',
						'surgery-cardiothoracicsurgerydivision' => 'Surgery - Cardiothoracic Surgery Division',
						'surgery-criticalcareservice' => 'Surgery - Critical Care Service',
						'surgery-generalsurgerydivision' => 'Surgery - General Surgery Division',
						'surgery-oncology' => 'Surgery - Oncology',
						'surgery-pediatricburnservice' => 'Surgery - Pediatric Burn Service',
						'surgery-pediatriccardiovascularsurgery' => 'Surgery - Pediatric Cardiovascular Surgery',
						'surgery-pediatricsurgeryservice' => 'Surgery - Pediatric Surgery Service',
						'surgery-plasticandreconstructivesurgerydivision' => 'Surgery - Plastic And Reconstructive Surgery Division',
						'surgery-thoracicsurgery' => 'Surgery - Thoracic Surgery',
						'surgery-transplantationdivision' => 'Surgery - Transplantation Division',
						'surgery-traumaservice' => 'Surgery - Trauma Service',
						'surgery-vascularsurgerydivision' => 'Surgery - Vascular Surgery Division',
						'surgeryoncology-breastsurgeryservice' => 'Surgery Oncology - Breast Surgery Service',
						'surgeryoncology-colorectalsurgeryservice' => 'Surgery Oncology - Colorectal Surgery Service',
						'surgeryoncology-surgicalendoscopyservice' => 'Surgery Oncology - Surgical Endoscopy Service',
						'surgeryoncology-surgicaloncologyservice' => 'Surgery Oncology - Surgical Oncology Service',
						'surgerypediatricsurgerydivision' => 'Surgery Pediatric Surgery Division',
						'uams-regionalprograms' => 'UAMS - Regional Programs',
						'universityrehab' => 'University Rehab',
						'urology' => 'Urology',
						'urology-pediatricurology' => 'Urology - Pediatric Urology',
	                ),
	            ),
        	),
        ),

		array(
          	'id'     => 'person_education',
          	'type'   => 'group',
          	'tab' => 'tab_edu',
	      	'clone'  => true,
	      	'sort_clone' => true,
	      	'fields' => array(
	            array(
	                'name' => 'Education Type',
	                'id'   => 'person_education_type',
	                'type' => 'select',
	                'options' => array(
	                	'University' => 'University',
						'Internship' => 'Internship',
						'Residency' => 'Residency',
						'Fellowship' => 'Fellowship',
						'AmbulatoryCareTraining' => 'Ambulatory Care Training',
						'Certificate' => 'Certificate',
						'ChildAbusePediatricsFellowship' => 'Child Abuse Pediatrics Fellowship',
						'Clinicaltraining' => 'Clinical training',
						'Diploma' => 'Diploma',
						'DoctorofOsteopathicMedicine' => 'Doctor of Osteopathic Medicine',
						'DoctorofVeterinaryMedicine' => 'Doctor of Veterinary Medicine',
						'Doctorate' => 'Doctorate',
						'Graduateschool' => 'Graduate school',
						'InternshipandResidency' => 'Internship and Residency',
						'Masters' => 'Masters',
						'MedicalSchool' => 'Medical School',
						'Nursingschool' => 'Nursing school',
						'OneYearofFellowship' => 'One Year of Fellowship',
						'PostDoctoralTraining' => 'Post Doctoral Training',
						'Post-graduatetraining' => 'Post-graduate training',
						'Pre-doctoralIntern' => 'Pre-doctoral Intern',
						'ResearchScholar' => 'Research Scholar',
						'Undergraduate' => 'Undergraduate',
	                ),
	            ),
	            array(
	                'name' => 'School',
	                'id'   => 'person_education_school',
	                'type' => 'select',
	                'options' =>  array(
	                	"AbingtonMemorialHospital" => "Abington Memorial Hospital",
						"AgaKhanUniversity" => "Aga Khan University",
						"AinShamsUniversitySchoolofMedicine" => "Ain Shams University School of Medicine",
						"AlbanyMedicalCollege" => "Albany Medical College",
						"AleppoUniversityMedicalSchool" => "Aleppo University Medical School",
						"AlexandriaUniversityHospital" => "Alexandria University Hospital",
						"AllIndiaInstituteofMedicalSciences" => "All India Institute of Medical Sciences",
						"AllamaIqbalMedicalCollege" => "Allama Iqbal Medical College",
						"AmericanUniversityofBeirut" => "American University of Beirut",
						"AnahuacUniversity" => "Anahuac University",
						"AndhraMedcialCollege" => "Andhra Medcial College",
						"ArgosyUniversity-FloridaSchoolofProfessionalPsychology" => "Argosy University - Florida School of Professional Psychology",
						"ArkansasChildrensHospital" => "Arkansas Children's Hospital",
						"ArkansasStateUniversity" => "Arkansas State University",
						"ArmedForcesInstituteofPathology" => "Armed Forces Institute of Pathology",
						"AssociatedUniversityofLouisvilleHospital" => "Associated University of Louisville Hospital",
						"AucklandCityHospitalStarshipChildrensHospital" => "Auckland City Hospital, Starship Children's Hospital",
						"BahriaCollege" => "Bahria College",
						"BangaloreMedicalCollegeBangaloreUniversity" => "Bangalore Medical College, Bangalore University",
						"Barnes-JewishHospital" => "Barnes-Jewish Hospital",
						"BarrowNeurologicalInstitute" => "Barrow Neurological Institute",
						"BascomPalmerEyeInstitute" => "Bascom Palmer Eye Institute",
						"BatonRougeGeneralMedicalCenter" => "Baton Rouge General Medical Center",
						"BaylorCollegeofMedicine" => "Baylor College of Medicine",
						"BaystateMedicalCenterTuftsUniversitySchoolofMedicine" => "Baystate Medical Center Tufts University School of Medicine",
						"BeaumontHealthSystem" => "Beaumont Health System",
						"BerajaMedicalInstitute" => "Beraja Medical Institute",
						"BharatiyaVidyaKendram" => "Bharatiya Vidya Kendram",
						"BostonChildrensHospital" => "Boston Children's Hospital",
						"BostonUniversity" => "Boston University",
						"BrighamandWomansHospital" => "Brigham and Woman's Hospital",
						"BrightonUniversity" => "Brighton University",
						"BrookdaleUniversityHospital" => "Brookdale University Hospital",
						"BrookeArmyMedicalCenter" => "Brooke Army Medical Center",
						"BrooklynHospital" => "Brooklyn Hospital",
						"BrownUniversity" => "Brown University",
						"BrynMawrCollege" => "Bryn Mawr College",
						"CadetCollegeHasanabdal" => "Cadet College Hasanabdal",
						"CampbellClinic" => "Campbell Clinic",
						"CarolinasMedicalCenter" => "Carolinas Medical Center",
						"CaseWesternReserveUniversitySchoolofMedicine" => "Case Western Reserve University School of Medicine",
						"CentenaryCollegeofLouisiana" => "Centenary College of Louisiana",
						"CentrodeEstudiosUniversitariosXochicalco" => "Centro de Estudios Universitarios Xochicalco",
						"ChennaiMedicalCollege" => "Chennai Medical College",
						"ChicagoCollegeofOsteopathicMedicine" => "Chicago College of Osteopathic Medicine",
						"ChicagoMedicalSchool" => "Chicago Medical School",
						"ChildrensClinic" => "Children's Clinic",
						"ChildrensHospitalColorado" => "Children's Hospital Colorado",
						"ChildrensHospitalMedicalCenter" => "Children's Hospital Medical Center",
						"ChildrensHospitalofAkron" => "Children's Hospital of Akron",
						"ChildrensHospitalofMichigan" => "Children's Hospital of Michigan",
						"ChildrensHospitalofPhiladelphia" => "Children's Hospital of Philadelphia",
						"ChildrensHospitalofBoston" => "Children’s Hospital of Boston",
						"ChildrensHospitalofColorado" => "Children’s Hospital of Colorado",
						"ChildrensMemorialHospital" => "Children’s? Memorial Hospital",
						"ChristHospital" => "Christ Hospital",
						"ChristianMedicalCollegeandHospital" => "Christian Medical College and Hospital",
						"CincinnatiChildrensHospitalMedicalCenter" => "Cincinnati Children's Hospital Medical Center",
						"ClevelandClinic" => "Cleveland Clinic",
						"ClevelandClinicTaussigCancerCenter" => "Cleveland Clinic Taussig Cancer Center",
						"ClinicsoftheCityofCologne" => "Clinics of the City of Cologne",
						"ClinicsoftheCityofCologneGermany" => "Clinics of the City of Cologne, Germany",
						"CloptonClinic" => "Clopton Clinic",
						"CoimbatoreMedicalCollege" => "Coimbatore Medical College",
						"ColoradoStateUniversity" => "Colorado State University",
						"ColumbiaUniversityMailmanSchoolofPublicHealth" => "Columbia University Mailman School of Public Health",
						"ColumbiaUniversitySchoolofMedicine" => "Columbia University School of Medicine",
						"CookCountyHospital" => "Cook County Hospital",
						"CPCMentalHealthServices" => "CPC Mental Health Services",
						"CreightonUniversitySchoolofMedicine" => "Creighton University School of Medicine",
						"DalhousieUniversity" => "Dalhousie University",
						"DamascusUniversitySchoolofMedicine" => "Damascus University School of Medicine",
						"DeccanCollegeofMedicalSciences" => "Deccan College of Medical Sciences",
						"DetroitOsteopathicHospitalCorporation" => "Detroit Osteopathic Hospital Corporation",
						"DokuzEylulUniversitySchoolofMedicine" => "Dokuz Eylul University School of Medicine",
						"DowMedicalCollege-KarachiUniversity" => "Dow Medical College - Karachi University",
						"DrexelUniversityCollegeofMedicine" => "Drexel University College of Medicine",
						"DukeUniversity" => "Duke University",
						"DukeUniversityMedicalCenter" => "Duke University Medical Center",
						"DukeUniversitySchoolofMedicine" => "Duke University School of Medicine",
						"EastTennesseeStateUniversity" => "East Tennessee State University",
						"EastTennesseeStateUniversityQuillenCollegeofMedicine" => "East Tennessee State University Quillen College of Medicine",
						"EasternVirginiaMedicalSchool" => "Eastern Virginia Medical School",
						"EdinburghUniversityMedicalSchool" => "Edinburgh University Medical School",
						"EmoryUniversity" => "Emory University",
						"EmoryUniversitySchoolofMedicine" => "Emory University School of Medicine",
						"EnglewoodHospitalSchoolofNursing" => "Englewood Hospital School of Nursing",
						"EuropeanAssociationofUrology" => "European Association of Urology",
						"FaridpurMedicalCollege" => "Faridpur Medical College",
						"FirstMoscowMedicalInstitute" => "First Moscow Medical Institute",
						"FloridaHospital" => "Florida Hospital",
						"FloridaInstituteofTechnology" => "Florida Institute of Technology",
						"FloridaOrthopaedicInstitute" => "Florida Orthopaedic Institute",
						"ForestParkHospital" => "Forest Park Hospital",
						"FranklinSquareHospitalCenter" => "Franklin Square Hospital Center",
						"GeisingerMedicalCenter" => "Geisinger Medical Center",
						"GeneralArmyHospital" => "General Army Hospital",
						"GeneralHospitalNumber1" => "General Hospital Number 1",
						"GeneralHospitalofChartres-France" => "General Hospital of Chartres-France",
						"GeorgeWashingtonUniversityHealthSciencesCenter" => "George Washington University Health Sciences Center",
						"GeorgetownUniversity" => "Georgetown University",
						"GeorgiaSouthwesternStateUniversity" => "Georgia Southwestern State University",
						"GloucestershireHospitals" => "Gloucestershire Hospitals",
						"GovernmentMedicalCollege" => "Government Medical College",
						"GrandCanyonUniversity" => "Grand Canyon University",
						"GrantMedicalCollege" => "Grant Medical College",
						"GreaterBaltimoreMedicalCenter" => "Greater Baltimore Medical Center",
						"HacettepeUniversity" => "Hacettepe University",
						"HammersmithHospital" => "Hammersmith Hospital",
						"HannemanUniversityMonmouthMedicalCenter" => "Hanneman University, Monmouth Medical Center,",
						"HardingUniversity" => "Harding University",
						"HarvardHospitals-BethIsraelDeaconessMedicalCenter" => "Harvard Hospitals-Beth Israel Deaconess Medical Center",
						"HarvardMedicalSchool" => "Harvard Medical School",
						"HarvardMedicalSchoolMassachusettsEyeandEarInfirmary" => "Harvard Medical School, Massachusetts Eye and Ear Infirmary",
						"HarvardSchoolofPublicHealth" => "Harvard School of Public Health",
						"HarvardUniversityBrigham&WomensHospital" => "Harvard University, Brigham & Women’s Hospital",
						"HaydarpasaNumuneStateTeachingHospital" => "Haydarpasa Numune State Teaching Hospital",
						"HealthCenterHercegNovi-Montenegro" => "Health Center Herceg Novi - Montenegro",
						"HendrixCollege" => "Hendrix College",
						"HenryFordHospital" => "Henry Ford Hospital",
						"HersheyMedicalSchoolofPennsylvaniaStateUniversity" => "Hershey Medical School of Pennsylvania State University",
						"HopeHospital" => "Hope Hospital",
						"HospitaldeNinosPedrodeElizalde" => "Hospital de Ninos Pedro de Elizalde",
						"HospitalforSickChildreninToronto" => "Hospital for Sick Children in Toronto",
						"HowardHughesMedicalInstituteNationalInstitutesofHealth" => "Howard Hughes Medical Institute / National Institutes of Health",
						"HurleyMedicalCenter" => "Hurley Medical Center",
						"ImperialCollegeLondon" => "Imperial College London",
						"IndianaUniversityMedicalCenter" => "Indiana University Medical Center",
						"IndianaUniversitySchoolofMedicine" => "Indiana University School of Medicine",
						"Inselspital(UniversityHospitalofBern)" => "Inselspital (University Hospital of Bern)",
						"InstituteofDiagnosticRadiologyUniversityClinics" => "Institute of Diagnostic Radiology, University Clinics",
						"InstituteofGraduateHealthSciences" => "Institute of Graduate Health Sciences",
						"InterfaithMedicalCenter" => "Interfaith Medical Center",
						"IowaStateUniversity" => "Iowa State University",
						"IpswichHospital" => "Ipswich Hospital",
						"IstanbulUniversitySchoolofMedicine" => "Istanbul University, School of Medicine",
						"JacksonMemorialHospital" => "Jackson Memorial Hospital",
						"JacobiMedicalCenter" => "Jacobi Medical Center",
						"JawaharlalInstituteofPostGraduateMedicaleducationandResearch" => "Jawaharlal Institute of Post Graduate Medical education and Research",
						"JohnABurnsSchoolofMedicine" => "John A. Burns School of Medicine",
						"JohnHStrogerHospitalofCookCounty" => "John H. Stroger Hospital of Cook County",
						"JohnNInsallTravelingFellowship" => "John N. Insall Traveling Fellowship",
						"JohnRadcliffeUniversityHospital" => "John Radcliffe University Hospital",
						"JohnsHopkinsUniversity" => "Johns Hopkins University",
						"JordanUniversityofScienceandTechnology" => "Jordan University of Science and Technology",
						"KansasCityUniversityofMedicineandBiosciences" => "Kansas City University of Medicine and Biosciences",
						"KasturbaMedicalCollege" => "Kasturba Medical College",
						"KeeslerUSAirForceMedicalCenter" => "Keesler U. S. Air Force Medical Center",
						"KhyberMedicalCollegeUniversityofPeshawar" => "Khyber Medical College, University of Peshawar",
						"KingEdwardMedicalCollege" => "King Edward Medical College",
						"KingFaisalUniversity" => "King Faisal University",
						"KingGeorgeHospital" => "King George Hospital",
						"KOBBACentralHospital" => "KOBBA Central Hospital",
						"LaSalleUniversity" => "La Salle University",
						"LamarUniversity" => "Lamar University",
						"LankenauHospital" => "Lankenau Hospital",
						"LehighUniversity" => "Lehigh University",
						"LenoxHillHospital" => "Lenox Hill Hospital",
						"LettermanArmyMedicalCenter" => "Letterman Army Medical Center",
						"LincolnMedicalCenter" => "Lincoln Medical Center",
						"LokNayakHospital" => "Lok Nayak Hospital",
						"LokmanyaTilakMedicalCollegeMumbaiUniversity" => "Lokmanya Tilak Medical College, Mumbai University",
						"LomaLindaUniversityCollegeofMedicine" => "Loma Linda University College of Medicine",
						"LongIslandCollegeHospital" => "Long Island College Hospital",
						"LouisianaStateUniversity" => "Louisiana State University",
						"LouisianaStateUniversityHealthSciencesCenter" => "Louisiana State University Health Sciences Center",
						"LouisianaStateUniversityMedicalCenter" => "Louisiana State University Medical Center",
						"LouisianaStateUniversitySchoolofMedicine" => "Louisiana State University School of Medicine",
						"LoyolaUniversityNewOrleans" => "Loyola University New Orleans",
						"LoyolaUniversityofChicago" => "Loyola University of Chicago",
						"LoyolaUniversityofChicago-EdwardHinesJrHospitalandFosterGMcGawHospital" => "Loyola University of Chicago - Edward Hines Jr. Veterans Administration Hospital and Foster G. McGaw Hospital",
						"Lyceum-NorthwesternFQDMedicalFoundation" => "Lyceum-Northwestern F.Q.D. Medical Foundation",
						"MadiganArmyMedicalCenter" => "Madigan Army Medical Center",
						"MahatmaGandhiInstituteofMedicalSciences" => "Mahatma Gandhi Institute of Medical Sciences",
						"MarshfieldClinic" => "Marshfield Clinic",
						"MaterHospital" => "Mater Hospital",
						"MaulanaAzadMedicalCollege" => "Maulana Azad Medical College",
						"MayoClinic" => "Mayo Clinic",
						"McGawMedicalCenterofNorthwesternUniversity" => "McGaw Medical Center of Northwestern University",
						"McGillUniversityMontreal" => "McGill University Montreal",
						"MedicalCollegeHospitalKottayam" => "Medical College Hospital, Kottayam",
						"MedicalCollegeHospitalTrivandrum" => "Medical College Hospital, Trivandrum",
						"MedicalCollegeofGeorgia" => "Medical College of Georgia",
						"MedicalCollegeofVirginia" => "Medical College of Virginia",
						"MedicalCollegeofWisconsin" => "Medical College of Wisconsin",
						"MedicalSchoolforInternationalHealthBenGurionUniversity" => "Medical School for International Health/Ben Gurion University",
						"MedicalSchoolofAnkaraUniversity" => "Medical School of Ankara University.",
						"MedicalSchooloftheNationalandKapodistrianUniversity" => "Medical School of the National and Kapodistrian University",
						"MedicalUniversityofSouthCarolina" => "Medical University of South Carolina",
						"MedicalUniversityoftheAmericas" => "Medical University of the Americas",
						"MeharryMedicalCollege" => "Meharry Medical College",
						"MemorialSloan-KetteringCancerCenter" => "Memorial Sloan-Kettering Cancer Center",
						"MercyHospitalStLouisUniversity" => "Mercy Hospital, St. Louis University",
						"MetaxaCancerHospitalofPiraeus" => "Metaxa Cancer Hospital of Piraeus",
						"MiltonSHersheyMedicalCenter" => "Milton S. Hershey Medical Center,",
						"MississippiStateUniversity" => "Mississippi State University",
						"MontefioreMedicalCenter" => "Montefiore Medical Center",
						"MoorfieldsEyeHospital" => "Moorfields Eye Hospital",
						"MountSinaiSchoolofMedicine" => "Mount Sinai School of Medicine",
						"MysoreMedicalCollege" => "Mysore Medical College",
						"NationalAutonomousUniversityofMexico" => "National Autonomous University of Mexico",
						"NationalHealthServiceHospitals" => "National Health Service Hospitals",
						"NationalInstituteofMedicalSciencesandNutrition“SalvadorZubiran”" => "National Institute of Medical Sciences and Nutrition “Salvador Zubiran”",
						"NationwideChildrensHospital" => "Nationwide Children's Hospital",
						"NEAWomensClinic" => "NEA Women's Clinic",
						"NewEnglandMedicalCenter" => "New England Medical Center",
						"NewMexicoVeteransAdministration-Albuquerque" => "New Mexico Veteran's Administration - Albuquerque",
						"NewYorkHospital&MedicalCenter" => "New York Hospital & Medical Center",
						"NewYorkMedicalCollege" => "New York Medical College",
						"NewYorkPresbyterianHospital" => "New York Presbyterian Hospital",
						"NewYorkUniversityMedicalCenter" => "New York University Medical Center",
						"NewYorkUniversitySacklerInstituteofGraduateBiomedicalSciences" => "New York University Sackler Institute of Graduate Biomedical Sciences",
						"NewYorkUniversitySchoolofMedicine" => "New York University School of Medicine",
						"NishtarMedicalCollege" => "Nishtar Medical College",
						"NJASchoolofPublicHealthUniversityOfSouthCarolina" => "NJA School of Public Health, University Of South Carolina",
						"NorthShore–LIJHealthSystem" => "North Shore – LIJ Health System",
						"NortheasternStateUniversity" => "Northeastern State University",
						"NorthwesternUniversity" => "Northwestern University",
						"NorthwickParkHospital" => "Northwick Park Hospital",
						"OchsnerClinicFoundation" => "Ochsner Clinic Foundation",
						"OhioStateUniversityMedicalCenter" => "Ohio State University Medical Center",
						"OklahomaHealthSciencesCenter" => "Oklahoma Health Sciences Center",
						"OklahomaStateUniversity" => "Oklahoma State University",
						"OregonHealthandScienceUniversity" => "Oregon Health and Science University",
						"OrthoCarolinaHip&KneeInstitute" => "OrthoCarolina Hip & Knee Institute",
						"OsmaniaMedicalCollegeNTRUniversity" => "Osmania Medical College, NTR University",
						"OuachitaBaptistUniversity" => "Ouachita Baptist University",
						"OurLadyofLourdesHospitalPhillipines" => "Our Lady of Lourdes Hospital, Phillipines",
						"OwasiHospital" => "Owasi Hospital",
						"PakistanAirForceCollege" => "Pakistan Air Force College",
						"PennState-HersheyMedicalCenter" => "Penn State - Hershey Medical Center",
						"PennStateCollegeofMedicineMiltonSHersheyMedicalCenter" => "Penn State College of Medicine, Milton S. Hershey Medical Center",
						"PennStateGeisingerMedicalCenter" => "Penn State Geisinger Medical Center",
						"PhilippineChildrensMedicalCenter" => "Philippine Children's Medical Center",
						"PhoenixIntegratedSurgicalInternsship" => "Phoenix Integrated Surgical Internsship",
						"PhysiciansMedicalCenterCarraway" => "Physician's Medical Center Carraway",
						"PolytechnicInstituteandStateUniversity" => "Polytechnic Institute and State University",
						"PonceSchoolofMedicine" => "Ponce School of Medicine",
						"PontificiaUniversidadCatolicadeChileSchoolofMedicine" => "Pontificia Universidad Catolica de Chile School of Medicine",
						"PurdueUniversity" => "Purdue University",
						"Quaid-i-AzamMedicalSchool" => "Quaid-i-Azam Medical School",
						"RainbowBabiesandChildrensHospital" => "Rainbow Babies and Children's Hospital",
						"RajendraMedicalCollege" => "Rajendra Medical College",
						"RangarayaMedicalCollege" => "Rangaraya Medical College",
						"RogersHighSchool" => "Rogers High School",
						"RossUniversitySchoolofMedicine" => "Ross University School of Medicine",
						"RoyalCollegeofPathologists" => "Royal College of Pathologists",
						"RoyalCollegeofPhysicians" => "Royal College of Physicians",
						"RoyalCollegeofSurgeons" => "Royal College of Surgeons",
						"RoyalInfirmaryofEdinburgh" => "Royal Infirmary of Edinburgh",
						"RoyalMelbourneHospital" => "Royal Melbourne Hospital",
						"RoyalNorthShoreHospital" => "Royal North Shore Hospital",
						"RoyalVictoriaHospital" => "Royal Victoria Hospital",
						"Ruhr-UniversityBochum" => "Ruhr-University Bochum",
						"RushMedicalCollege" => "Rush Medical College",
						"RushMedicalSchool" => "Rush Medical School",
						"RutgersUniversity" => "Rutgers University",
						"SamajsMedicalCollege" => "Samaj's Medical College",
						"SamfordUniversity" => "Samford University",
						"SawaiManSinghMedicalCollege" => "Sawai Man Singh Medical College",
						"SechenovsMoscowMedicalAcademy" => "Sechenov's Moscow Medical Academy",
						"SethGSMedicalCollegeandKEMHospitalMumbaiUniversity" => "Seth G. S. Medical College and KEM Hospital, Mumbai University",
						"SethGSMedicalCollegeandKemHospitalMumbaiUniversity" => "Seth G.S. Medical College and Kem Hospital, Mumbai University",
						"SetonHallSchoolofGraduateMedicalEducation" => "Seton Hall School of Graduate Medical Education",
						"SiddharthaMedicalCollege" => "Siddhartha Medical College",
						"Sinai-GraceHospitalWayneStateUniversity" => "Sinai-Grace Hospital/Wayne State University",
						"SorokaMedicalCenter" => "Soroka Medical Center",
						"SoutheastMissouriStateUniversityCollegeofNursing" => "Southeast Missouri State University, College of Nursing",
						"SouthernArkansasUniversity" => "Southern Arkansas University",
						"SouthernCollegeofOptometry" => "Southern College of Optometry",
						"SouthernIllinoisUniversity" => "Southern Illinois University",
						"SouthernUniversity" => "Southern University",
						"SouthwestMissouriStateUniversity" => "Southwest Missouri State University",
						"SriDevarajUrsMedicalCollege" => "Sri Devaraj Urs Medical College",
						"StElizabethsMedicalCenter" => "St. Elizabeth's Medical Center",
						"StGeorgesUniversityofMedicine" => "St. George's University of Medicine",
						"StLouisUniversityHealthSciencesCenter" => "St. Louis University Health Sciences Center",
						"StLouisUniversitySchoolofMedicine" => "St. Louis University School of Medicine",
						"StLukes-RooseveltHospitalCenter" => "St. Luke's -Roosevelt Hospital Center",
						"StLukesHospital" => "St. Luke's Hospital",
						"StThomasHospital" => "St.Thomas' Hospital",
						"StanfordUniversity" => "Stanford University",
						"StanleyMedicalCollege" => "Stanley Medical College",
						"StarshipChildrensHospital" => "Starship Children's Hospital",
						"SUNYDownstateMedicalCenter" => "SUNY Downstate Medical Center",
						"SUNYUpstateMedicalUniversity" => "SUNY Upstate Medical University",
						"SwedishNeuroscienceInstitute" => "Swedish Neuroscience Institute",
						"TechnicalUniversityHospitalofMunich" => "Technical University Hospital of Munich",
						"TehranUniversitySchoolofMedicine" => "Tehran University School of Medicine",
						"TempleUniversitySchoolofMedicine" => "Temple University School of Medicine",
						"TexasA&MInternationalUniversity" => "Texas A&M International University",
						"TexasA&MUniversity-CollegeofMedicine" => "Texas A&M University - College of Medicine",
						"TexasTechUniversityHealthScienceCenter" => "Texas Tech University Health Science Center",
						"ThanjavurMedicalCollege" => "Thanjavur Medical College",
						"TheHospitalforSickChildren" => "The Hospital for Sick Children",
						"TheMethodistHospital" => "The Methodist Hospital",
						"TheOhioStateUniversity" => "The Ohio State University",
						"ThePennsylvaniaStateUniversity" => "The Pennsylvania State University",
						"TheTamilnaduDrMGRMedicalUniversity" => "The Tamilnadu Dr. M.G.R. Medical University",
						"TheUniversityofTexasHealthScienceCenter" => "The University of Texas Health Science Center",
						"ThomasJeffersonUniversity" => "Thomas Jefferson University",
						"TishreenUniversitySchoolofMedicine" => "Tishreen University School of Medicine",
						"TongjiMedicalCollege" => "Tongji Medical College",
						"TouroUniversityCollegeofOsteopathicMedicine" => "Touro University College of Osteopathic Medicine",
						"TuftsUniversitySchoolofMedicine" => "Tufts University School of Medicine",
						"TulaneUniversityMedicalSchool" => "Tulane University Medical School",
						"TulsaMedicalCollege" => "Tulsa Medical College",
						"UAMSNorthwest" => "UAMS Northwest",
						"UAMSSouthCentral" => "UAMS South Central",
						"UAMSWest" => "UAMS West",
						"UCLACedarsSinai" => "UCLA, Cedars Sinai",
						"UlsterHospital" => "Ulster Hospital",
						"UnitedStatesMilitaryAcademyatWestpoint" => "United States Military Academy at Westpoint",
						"UniversidaddeBuenosAiresFacultaddeMedicina" => "Universidad de Buenos Aires. Facultad de Medicina",
						"UniversidaddeZaragoza" => "Universidad de Zaragoza",
						"UniversidaddelValleSchoolofMedicine" => "Universidad del Valle School of Medicine",
						"UniversityClinic-BezanijskaKosa" => "University Clinic - Bezanijska Kosa",
						"UniversityCollege" => "University College",
						"UniversityCollegeofMedicalSciences" => "University College of Medical Sciences",
						"UniversityHospital" => "University Hospital",
						"UniversityHospitalofZurich" => "University Hospital of Zurich",
						"UniversityofAachen" => "University of Aachen",
						"UniversityofAlabamaatBirmingham" => "University of Alabama at Birmingham",
						"UniversityofAlabamaatTuscaloosa" => "University of Alabama at Tuscaloosa",
						"UniversityofAlabamaSchoolofMedicine" => "University of Alabama School of Medicine",
						"UniversityofAnkara" => "University of Ankara",
						"UniversityofArizonaCollegeofMedicine" => "University of Arizona College of Medicine",
						"UniversityofArkansasatFayetteville" => "University of Arkansas at Fayetteville",
						"UniversityofArkansasatLittleRock" => "University of Arkansas at Little Rock",
						"UniversityofArkansasatPineBluff" => "University of Arkansas at Pine Bluff",
						"UniversityofArkansasforMedicalSciences" => "University of Arkansas for Medical Sciences",
						"UniversityofArkansasforMedicalSciences-FayeBoozmanCollegeofPublicHealth" => "University of Arkansas for Medical Sciences - Faye Boozman College of Public Health",
						"UniversityofArkansasforMedicalSciences-JonesEyeInstitute" => "University of Arkansas for Medical Sciences - Jones Eye Institute",
						"UniversityofBelgrade" => "University of Belgrade",
						"UniversityofCalgary" => "University of Calgary",
						"UniversityofCaliforniaatLosAngeles" => "University of California at Los Angeles",
						"UniversityofCaliforniaatSanDiego" => "University of California at San Diego",
						"UniversityofCaliforniaatSanFrancisco" => "University of California at San Francisco",
						"UniversityofCentralArkansas" => "University of Central Arkansas",
						"UniversityofChicagoHospitals" => "University of Chicago Hospitals",
						"UniversityofChile" => "University of Chile",
						"UniversityofCincinnati" => "University of Cincinnati",
						"UniversityofCologne" => "University of Cologne",
						"UniversityofColorado" => "University of Colorado",
						"UniversityofColoradoDenverSchoolofMedicine" => "University of Colorado Denver School of Medicine",
						"UniversityofColoradoHealthSciencesCenter" => "University of Colorado Health Sciences Center",
						"UniversityofColoradoSchoolofMedicine" => "University of Colorado School of Medicine",
						"UniversityofConnecticutHealthCenter" => "University of Connecticut Health Center",
						"UniversityofDayton" => "University of Dayton",
						"UniversityofDehli" => "University of Dehli",
						"UniversityofDhaka" => "University of Dhaka",
						"UniversityofEastRamonMagsaysayMemorialMedicalCente" => "University of East Ramon Magsaysay Memorial Medical Cente",
						"UniversityofFloridaatGainesville" => "University of Florida at Gainesville",
						"UniversityofFloridaatJacksonville" => "University of Florida at Jacksonville",
						"UniversityofGlasgow" => "University of Glasgow",
						"UniversityofHacettepe" => "University of Hacettepe",
						"UniversityofHalle" => "University of Halle",
						"UniversityofIbadan" => "University of Ibadan",
						"UniversityofIllinois" => "University of Illinois",
						"UniversityofIlorinTeachingHospital" => "University of Ilorin Teaching Hospital",
						"UniversityofIowaHospitalsandClinics" => "University of Iowa Hospitals and Clinics",
						"UniversityofIowaCollegeofMedicine" => "University of Iowa, College of Medicine",
						"UniversityofKansas" => "University of Kansas",
						"UniversityofKentucky" => "University of Kentucky",
						"UniversityofKentuckyMarkeyCancerCenter" => "University of Kentucky Markey Cancer Center",
						"UniversityofKerala" => "University of Kerala",
						"UniversityofLondon" => "University of London",
						"UniversityofLondon-RoyalCollegeofPathologists" => "University of London - Royal College of Pathologists",
						"UniversityofLouisville" => "University of Louisville",
						"UniversityofMarylandHospital" => "University of Maryland Hospital",
						"UniversityofMassachusettsMedicalCenter" => "University of Massachusetts Medical Center",
						"UniversityofMedicineandDentistryofNewJersey" => "University of Medicine and Dentistry of New Jersey",
						"UniversityofMiamiHealthSystem" => "University of Miami Health System",
						"UniversityofMiamiMillerSchoolofMedicine" => "University of Miami Miller School of Medicine",
						"UniversityofMichigan" => "University of Michigan",
						"UniversityofMinnesota" => "University of Minnesota",
						"UniversityofMississippiMedicalCenter" => "University of Mississippi Medical Center",
						"UniversityofMissouri" => "University of Missouri",
						"UniversityofNebraska" => "University of Nebraska",
						"UniversityofNevadaSchoolofMedicine" => "University of Nevada School of Medicine",
						"UniversityofNewMexicoHealthSciencesCenter" => "University of New Mexico Health Sciences Center",
						"UniversityofNewMexicoSchoolofMedicine" => "University of New Mexico School of Medicine",
						"UniversityofNorthCarolinaatChapelHill" => "University of North Carolina at Chapel Hill",
						"UniversityofNorthTexasHealthScienceCenter" => "University of North Texas Health Science Center",
						"UniversityofOklahomaatTulsa" => "University of Oklahoma at Tulsa",
						"UniversityofOklahomaCollegeofMedicine" => "University of Oklahoma College of Medicine",
						"UniversityofOklahomaHealthSciencesCenter" => "University of Oklahoma, Health Sciences Center",
						"UniversityofPadua" => "University of Padua",
						"UniversityofParisDescartes" => "University of Paris Descartes",
						"UniversityofPatras" => "University of Patras",
						"UniversityofPennsylvaniaGraduateSchoolofEducation" => "University of Pennsylvania Graduate School of Education",
						"UniversityofPennsylvaniaPerelmanSchoolofMedicine" => "University of Pennsylvania Perelman School of Medicine",
						"UniversityofPisa" => "University of Pisa",
						"UniversityofPittsburghSchoolofMedicine" => "University of Pittsburgh School of Medicine",
						"UniversityofPuertoRicoSchoolofMedicine" => "University of Puerto Rico, School of Medicine",
						"UniversityofPunjab-KingEdwardMedicalCollege" => "University of Punjab - King Edward Medical College",
						"UniversityofRochesterSchoolofMedicineandDentistry" => "University of Rochester School of Medicine and Dentistry",
						"UniversityofRochesterStrongMemorialHospital" => "University of Rochester/Strong Memorial Hospital",
						"UniversityofSouthAlabama" => "University of South Alabama",
						"UniversityofSouthCarolinaSchoolofMedicine" => "University of South Carolina School of Medicine",
						"UniversityofSouthDakota" => "University of South Dakota",
						"UniversityofSouthFlorida" => "University of South Florida",
						"UniversityofSouthernCaliforniaSchoolofMedicine" => "University of Southern California School of Medicine",
						"UniversityofSydneyRoyalNorthShoreHospital" => "University of Sydney, Royal North Shore Hospital",
						"UniversityofTennessee" => "University of Tennessee",
						"UniversityofTexas" => "University of Texas",
						"UniversityofTexasGraduateSchoolofBiomedicalSciences" => "University of Texas Graduate School of Biomedical Sciences",
						"UniversityofTexasMDAndersonCancerCenter" => "University of Texas M.D. Anderson Cancer Center",
						"UniversityofTexasMD-AndersonCancerCenter" => "University of Texas MD - Anderson Cancer Center",
						"UniversityofTexasMedicalBranch" => "University of Texas Medical Branch",
						"UniversityofTexasMedicalSchoolatGalveston" => "University of Texas Medical School at Galveston",
						"UniversityofTexasMedicalSchoolatHouston" => "University of Texas Medical School at Houston",
						"UniversityofTexasSouthwesternMedicalCenter" => "University of Texas Southwestern Medical Center",
						"UniversityoftheEastRamonMagsaysayMemorialMedicalCenter" => "University of the East Ramon Magsaysay Memorial Medical Center",
						"UniversityoftheSciences" => "University of the Sciences",
						"UniversityoftheStateofNewYork" => "University of the State of New York",
						"UniversityoftheWestIndies" => "University of the West Indies",
						"UniversityofToronto" => "University of Toronto",
						"UniversityofUtah" => "University of Utah",
						"UniversityofValparaiso" => "University of Valparaiso",
						"UniversityofVermont" => "University of Vermont",
						"UniversityofVirginia" => "University of Virginia",
						"UniversityofVirginiaHealthSystem" => "University of Virginia Health System",
						"UniversityofVirginiaSchoolofMedicine" => "University of Virginia School of Medicine",
						"UniversityofWalesCollegeofMedicine" => "University of Wales College of Medicine",
						"UniversityofWashington" => "University of Washington",
						"UniversityofWashingtonSchoolofMedicine" => "University of Washington School of Medicine",
						"UniversityofWisconsin" => "University of Wisconsin",
						"UniversityofWürzburg" => "University of Würzburg",
						"UpledgerInstitute" => "Upledger Institute",
						"UppsalaUniversity" => "Uppsala University",
						"UtahStateUniversity" => "Utah State University",
						"VanderbiltUniversity" => "Vanderbilt University",
						"VeteransAffairsCaribbeanHealthcareSystems" => "Veterans Affairs Caribbean Healthcare Systems",
						"WakeForestUniversity" => "Wake Forest University",
						"WalterReedArmyMedicalCenter" => "Walter Reed Army Medical Center",
						"WashingtonUniversity" => "Washington University",
						"WashingtonUniversitySchoolofMedicine" => "Washington University School of Medicine",
						"WayneStateUniversity" => "Wayne State University",
						"WeillCornellMedicalCenter" => "Weill Cornell Medical Center",
						"WelshNationalSchoolofMedicineCardiffUniversitySchoolofMedicine" => "Welsh National School of Medicine/Cardiff University School of Medicine",
						"WestVirginiaUniversity" => "West Virginia University",
						"WhippsCrossUniversityHospital" => "Whipps Cross University Hospital,",
						"WhiteabbeyHospital" => "Whiteabbey Hospital",
						"WilfordHallUSAirForceMedicalCenter" => "Wilford Hall U. S. Air Force Medical Center",
						"WillsEyeHospital" => "Wills Eye Hospital",
						"WishardMemorialHospital" => "Wishard Memorial Hospital",
						"WyckoffHeightsMedicalCenter" => "Wyckoff Heights Medical Center",
						"YaleUniversityDivinitySchool" => "Yale University Divinity School",
						"YaleUniversitySchoolofMedicine" => "Yale University School of Medicine",
	                ),
	            ),
	            array(
	                'name'    => 'Desctiption',
	                'id'      => 'person_education_description',
	                'type'    => 'text',
	            ),
        	),
        ),

		array(
          	'id'     => 'physician_boards',
          	'type'   => 'group',
          	'tab' => 'tab_edu',
	      	'clone'  => true,
	      	'sort_clone' => true,
	      	'fields' => array(
	            array(
	                'name' => 'Boards',
	                'id'   => 'physician_boards',
	                'type' => 'select',
	                'options' => array(
	                	"AddedCertificationinlongtermcareandhomecare" => "Added Certification in longterm care and home care",
						"AddictionPsychiatry" => "Addiction Psychiatry",
						"AdvanceCertifiedAlcohol" => "Advance Certified Alcohol",
						"AdvancedCardiovascularLifeSupport(ACLS)" => "Advanced Cardiovascular Life Support (ACLS)",
						"AdvancedTraumaLifeSupport" => "Advanced Trauma Life Support",
						"AdvancedTraumaLifeSupportInstructor" => "Advanced Trauma Life Support Instructor",
						"AllergyandImmunology" => "Allergy and Immunology",
						"AmericanAcademyofAudiology" => "American Academy of Audiology",
						"AmericanAcademyofDermatology" => "American Academy of Dermatology",
						"AmericanAcademyofFamilyPhysicians" => "American Academy of Family Physicians",
						"AmericanAcademyofNeurology" => "American Academy of Neurology",
						"AmericanAcademyofNursePractitioners" => "American Academy of Nurse Practitioners",
						"AmericanAcademyofOphthalmology" => "American Academy of Ophthalmology",
						"AmericanAcademyofPediatrics" => "American Academy of Pediatrics",
						"AmericanAcademyofPhysicalMedicineandRehabilitation" => "American Academy of Physical Medicine and Rehabilitation",
						"AmericanAcademyofSleepMedicine" => "American Academy of Sleep Medicine",
						"AmericanAssociationforWomenRadiologists" => "American Association for Women Radiologists",
						"AmericanBoardofAllergyandImmunology" => "American Board of Allergy and Immunology",
						"AmericanBoardofAnatomic-ClinicalPathology" => "American Board of Anatomic - Clinical Pathology",
						"AmericanBoardofAnesthesiology" => "American Board of Anesthesiology",
						"AmericanBoardofCardiovascularMedicine" => "American Board of Cardiovascular Medicine",
						"AmericanBoardofClinicPharmacology" => "American Board of Clinic Pharmacology",
						"AmericanBoardofColonandRectalSurgery" => "American Board of Colon and Rectal Surgery",
						"AmericanBoardofDermatology" => "American Board of Dermatology",
						"AmericanBoardofDiagnosticRadiology" => "American Board of Diagnostic Radiology",
						"AmericanBoardofEchocardiography" => "American Board of Echocardiography",
						"AmericanBoardofElectrodiagnosticMedicine" => "American Board of Electrodiagnostic Medicine",
						"AmericanBoardofEmergencyMedicine" => "American Board of Emergency Medicine",
						"AmericanBoardofEndocrinologyDiabetesandMetabolism" => "American Board of Endocrinology, Diabetes and Metabolism",
						"AmericanBoardofFacialPlasticandReconstructiveSurgery" => "American Board of Facial Plastic and Reconstructive Surgery",
						"AmericanBoardofFamilyMedicine" => "American Board of Family Medicine",
						"AmericanBoardofFamilyPractice" => "American Board of Family Practice",
						"AmericanBoardofFamilyPracticeGeriatricCertification" => "American Board of Family Practice, Geriatric Certification",
						"AmericanBoardofGastroenterology" => "American Board of Gastroenterology",
						"AmericanBoardofGeriatricMedicine" => "American Board of Geriatric Medicine",
						"AmericanBoardofHematology" => "American Board of Hematology",
						"AmericanBoardofHospiceandPalliativeMedicine" => "American Board of Hospice and Palliative Medicine",
						"AmericanBoardofIndependentMedicalExaminers" => "American Board of Independent Medical Examiners",
						"AmericanBoardofInfecitousDiseases" => "American Board of Infecitous Diseases",
						"AmericanBoardofIntegrativeHolisticMedicine" => "American Board of Integrative Holistic Medicine",
						"AmericanBoardofInternalMedicine" => "American Board of Internal Medicine",
						"AmericanBoardofInternalMedicine-PulmonaryDisease" => "American Board of Internal Medicine - Pulmonary Disease",
						"AmericanBoardofInternalMedicine-CardiovascularDisease" => "American Board of Internal Medicine - Cardiovascular Disease",
						"AmericanBoardofInternalMedicine-ClinicalCardiacElectrophysiology" => "American Board of Internal Medicine - Clinical Cardiac Electrophysiology",
						"AmericanBoardofInternalMedicine-CriticalCare" => "American Board of Internal Medicine - Critical Care",
						"AmericanBoardofInternalMedicine-GastroenterologySubspecialty" => "American Board of Internal Medicine - Gastroenterology Subspecialty",
						"AmericanBoardofInternalMedicine-Geriatrics" => "American Board of Internal Medicine - Geriatrics",
						"AmericanBoardofInternalMedicine-InterventionalCardiology" => "American Board of Internal Medicine - Interventional Cardiology",
						"AmericanBoardofInternalMedicine-Nephrology" => "American Board of Internal Medicine - Nephrology",
						"AmericanBoardofInternalMedicine-RheumatologySub-Specialty" => "American Board of Internal Medicine - Rheumatology Sub-Specialty",
						"AmericanBoardofInternalMedicine-SleepMedicine" => "American Board of Internal Medicine - Sleep Medicine",
						"AmericanBoardofInternalMedicine-SubspecialtyRheumatology" => "American Board of Internal Medicine - Subspecialty Rheumatology",
						"AmericanBoardofInternalMedicineHematology" => "American Board of Internal Medicine, Hematology",
						"AmericanBoardofInternalMedicineInfectiousDiseasesSubspecialty" => "American Board of Internal Medicine, Infectious Diseases Subspecialty",
						"AmericanBoardofInternalMedicineMedicalOncology" => "American Board of Internal Medicine, Medical Oncology",
						"AmericanBoardofInternalMedicineOncology" => "American Board of Internal Medicine, Oncology",
						"AmericanBoardofInterventionalCardiology" => "American Board of Interventional Cardiology",
						"AmericanBoardofMedicalGenetics" => "American Board of Medical Genetics",
						"AmericanBoardofMedicalOncology" => "American Board of Medical Oncology",
						"AmericanBoardofMedicalSpecialties-Allergy&Immunology" => "American Board of Medical Specialties - Allergy & Immunology",
						"AmericanBoardofMedicalSpecialties-Pediatrics" => "American Board of Medical Specialties - Pediatrics",
						"AmericanBoardofNeurologicalSurgery" => "American Board of Neurological Surgery",
						"AmericanBoardofNuclearCardiology" => "American Board of Nuclear Cardiology",
						"AmericanBoardofNuclearMedicine(ABNM)" => "American Board of Nuclear Medicine (ABNM)",
						"AmericanBoardofObstetricsandGynecology" => "American Board of Obstetrics and Gynecology",
						"AmericanBoardofObstetricsandGynecology-FemalePelvicMedicineandReconstructiveSurgery" => "American Board of Obstetrics and Gynecology - Female Pelvic Medicine and Reconstructive Surgery",
						"AmericanBoardofObstetricsandGynecology-FemalePelvicMedicine&ReconstructiveSurgery" => "American Board of Obstetrics and Gynecology - Female Pelvic Medicine & Reconstructive Surgery",
						"AmericanBoardofObstetricsandGynecology-GynecologicOncology" => "American Board of Obstetrics and Gynecology - Gynecologic Oncology",
						"AmericanBoardofOpththalmology" => "American Board of Opththalmology",
						"AmericanBoardofOrthopaedicSurgeons" => "American Board of Orthopaedic Surgeons",
						"AmericanBoardofOtolaryngology" => "American Board of Otolaryngology",
						"AmericanBoardofOtolaryngology-HeadandNeckSurgery" => "American Board of Otolaryngology - Head and Neck Surgery",
						"AmericanBoardofPathology" => "American Board of Pathology",
						"AmericanBoardofPathology-AnatomicandClinicalPathology" => "American Board of Pathology - Anatomic and Clinical Pathology",
						"AmericanBoardofPathology-ClinicalPathology" => "American Board of Pathology - Clinical Pathology",
						"AmericanBoardofPathologyBloodBankingandTransfusionMedicine" => "American Board of Pathology, Blood Banking and Transfusion Medicine",
						"AmericanBoardofPathologyForensicPathology" => "American Board of Pathology, Forensic Pathology",
						"AmericanBoardofPathologyMolecularPathology" => "American Board of Pathology, Molecular Pathology",
						"AmericanBoardofPediatricCardiology" => "American Board of Pediatric Cardiology",
						"AmericanBoardofPediatricPulmonology" => "American Board of Pediatric Pulmonology",
						"AmericanBoardofPediatrics" => "American Board of Pediatrics",
						"AmericanBoardofPediatrics-PediatricEmergencyMedicine" => "American Board of Pediatrics - Pediatric Emergency Medicine",
						"AmericanBoardofPediatrics-PediatricNephrology" => "American Board of Pediatrics - Pediatric Nephrology",
						"AmericanBoardofPhysicalMedicine&Rehabilitation" => "American Board of Physical Medicine & Rehabilitation",
						"AmericanBoardofPhysicianSpecialties-FamilyPractice" => "American Board of Physician Specialties - Family Practice",
						"AmericanBoardofPlasticSurgery" => "American Board of Plastic Surgery",
						"AmericanBoardofPreventiveMedicine" => "American Board of Preventive Medicine",
						"AmericanBoardofPreventiveMedicine-ClinicalInformaticsSubspecialty" => "American Board of Preventive Medicine - Clinical Informatics Subspecialty",
						"AmericanBoardofProfessionalPsychology-AmericanBoardofClinicalNeuropsychology" => "American Board of Professional Psychology - American Board of,nical Neuropsychology",
						"AmericanBoardofPsychiatry-ForensicPsychiatry" => "American Board of Psychiatry - Forensic Psychiatry",
						"AmericanBoardofPsychiatryandNeurology" => "American Board of Psychiatry and Neurology",
						"AmericanBoardofPsychiatryandNeurology-AddedQualificationsinClinicalNeurophysiology" => "American Board of Psychiatry and Neurology -  Added Qualifications in Clinical Neurophysiology",
						"AmericanBoardofPsychiatryandNeurology-ChildandAdolescentPsychiatry" => "American Board of Psychiatry and Neurology - Child and Adolescent Psychiatry",
						"AmericanBoardofPsychiatryandNeurology-ChildNeurology" => "American Board of Psychiatry and Neurology - Child Neurology",
						"AmericanBoardofPsychiatryandNeurology-ClinicalNeuropsychology" => "American Board of Psychiatry and Neurology - Clinical Neuropsychology",
						"AmericanBoardofPsychiatryandNeurology-Psychiatry" => "American Board of Psychiatry and Neurology - Psychiatry",
						"AmericanBoardofQualityAssuranceandUtilizationReviewPhysicians-HealthcareQualityandManagement/PatientSafety" => "American Board of Quality Assurance and Utilization Review Physicians-Healthcare Quality and Management/Patient Safety",
						"AmericanBoardofRadiology" => "American Board of Radiology",
						"AmericanBoardofRadiology-CAQinPediatricRadiology" => "American Board of Radiology - CAQ in Pediatric Radiology",
						"AmericanBoardofRadiology-DiagnosticRadiology" => "American Board of Radiology - Diagnostic Radiology",
						"AmericanBoardofRadiology-RadiationOncology" => "American Board of Radiology - Radiation Oncology",
						"AmericanBoardofRadiology-TherapeuticPhysics" => "American Board of Radiology - Therapeutic Physics",
						"AmericanBoardofSleepMedicine" => "American Board of Sleep Medicine",
						"AmericanBoardofSurgery" => "American Board of Surgery",
						"AmericanBoardofSurgery-SurgicalCriticalCare" => "American Board of Surgery - Surgical Critical Care",
						"AmericanBoardofSurgery-VascularSurgery" => "American Board of Surgery - Vascular Surgery",
						"AmericanBoardofSurgery-VascularSurgeryCertificate" => "American Board of Surgery - Vascular Surgery Certificate",
						"AmericanBoardofThoracicSurgery" => "American Board of Thoracic Surgery",
						"AmericanBoardofUrology" => "American Board of Urology",
						"AmericanBoardofVascularSurgery" => "American Board of Vascular Surgery",
						"AmericanCollegeofEndocrinology" => "American College of Endocrinology",
						"AmericanCollegeofObstetriciansandGynecologists" => "American College of Obstetricians and Gynecologists",
						"AmericanCollegeofObstetricsandGynecologyTaskForceonHormoneTherapy" => "American College of Obstetrics and Gynecology Task Force on Hormone Therapy",
						"AmericanCollegeofPhysicians" => "American College of Physicians",
						"AmericanCollegeofRadiology" => "American College of Radiology",
						"AmericanCollegeofSurgeons" => "American College of Surgeons",
						"AmericanCollegeofSurgeons-Fellow" => "American College of Surgeons - Fellow",
						"AmericanDiabetesAssociation" => "American Diabetes Association",
						"AmericanGeriatricsSociety" => "American Geriatrics Society",
						"AmericanHeartAssociation" => "American Heart Association",
						"AmericanInstituteofBalanceVestibularAssessmentandManagement" => "American Institute of Balance Vestibular Assessment and Management",
						"AmericanMedicalAssociation" => "American Medical Association",
						"AmericanMedicalStudentAssociation" => "American Medical Student Association",
						"AmericanMedicalWomensAssociation" => "American Medical Women's Association",
						"AmericanNursesCredentialingCenter" => "American Nurses Credentialing Center",
						"AmericanOccupationalTherapyAssociation" => "American Occupational Therapy Association",
						"AmericanPancreaticAssociation" => "American Pancreatic Association",
						"AmericanPhysicalTherapyAssociation" => "American Physical Therapy Association",
						"AmericanPsychiatricAssociation" => "American Psychiatric Association",
						"AmericanPsychologicalAssociation" => "American Psychological Association",
						"AmericanRoentgenRaySociety" => "American Roentgen Ray Society",
						"AmericanSocietyforGastrointestinalEndoscopy" => "American Society for Gastrointestinal Endoscopy",
						"AmericanSocietyforParenteralandEnteralNutrition" => "American Society for Parenteral and Enteral Nutrition",
						"AmericanSocietyofBreastSurgeons" => "American Society of Breast Surgeons",
						"AmericanSocietyofColonandRectalSurgeons" => "American Society of Colon and Rectal Surgeons",
						"AmericanSocietyofDermatopathology" => "American Society of Dermatopathology",
						"AmericanSocietyofReproductiveMedicine" => "American Society of Reproductive Medicine",
						"AmericanSocietyofTransplantSurgeons" => "American Society of Transplant Surgeons",
						"AmericanSpeech-Language-HearingAssociation" => "American Speech-Language-Hearing Association",
						"AmericanUrogynecologicSociety" => "American Urogynecologic Society",
						"AmericanUrologicalAssociation" => "American Urological Association",
						"AnatomicandClinicalPathology" => "Anatomic and Clinical Pathology",
						"ArkansasBoardofExaminersinSpeech-LanguagePathologyandAudiology" => "Arkansas Board of Examiners in Speech-Language Pathology and Audiology",
						"ArkansasDieteticAssociation" => "Arkansas Dietetic Association",
						"ArkansasGeriatricSociety" => "Arkansas Geriatric Society",
						"ArkansasLicensure" => "Arkansas Licensure",
						"ArkansasLicensure2009–Present" => "Arkansas Licensure, 2009 – Present",
						"ArkansasMedicalBoard" => "Arkansas Medical Board",
						"ArkansasMedicalSociety" => "Arkansas Medical Society",
						"ArkansasOccupationalTherapyAssociation" => "Arkansas Occupational Therapy Association",
						"ArkansasOphthalmologicalSociety" => "Arkansas Ophthalmological Society",
						"ArkansasPsychiatricSociety" => "Arkansas Psychiatric Society",
						"ArkansasPsychologyLicensure" => "Arkansas Psychology Licensure",
						"ArkansasSocialWorkLicensingBoard" => "Arkansas Social Work Licensing Board",
						"ArkansasSpeech-Language-HearingAssociation" => "Arkansas Speech-Language-Hearing Association",
						"ArkansasStateBoardofNursing" => "Arkansas State Board of Nursing",
						"ArkansasStateMedicalBoard" => "Arkansas State Medical Board",
						"ArkansasSubstanceAbuseCertification" => "Arkansas Substance Abuse Certification",
						"AssociationforAcademicSurgery" => "Association for Academic Surgery",
						"AssociationofAcademicPhysiatrists" => "Association of Academic Physiatrists",
						"AssociationofUniversityRadiologists" => "Association of University Radiologists",
						"AssociationofWomenPsychiatrists" => "Association of Women Psychiatrists",
						"AssociationofWomenSurgeons" => "Association of Women Surgeons",
						"Boardcertified1981Re-certified" => "Board certified 1981; Re-certified, 1989, 1996, 2003",
						"BoardCertifiedBehaviorAnalyst-LicensedPsychologicalExaminer" => "Board Certified Behavior Analyst - Licensed Psychological Examiner",
						"BoardCertifiedinFacialPlasticandReconstructiveSurgery" => "Board Certified in Facial Plastic and Reconstructive Surgery",
						"BoardCertifiedinPainManagement" => "Board Certified in Pain Management",
						"BoardCertified1984" => "Board Certified, 1984",
						"BritishBoardofUrology" => "British Board of Urology",
						"CertificateofAddedQualification-SportsMedicine" => "Certificate of Added Qualification - Sports Medicine",
						"CertificateofAddedQualification-VascularandInterventionalRadiology" => "Certificate of Added Qualification - Vascular and Interventional Radiology",
						"CertificateofAddedQualifications-SportsMedicine" => "Certificate of Added Qualifications - Sports Medicine",
						"CertificationBoardofNuclearCardiology" => "Certification Board of Nuclear Cardiology",
						"CertificationinMedicalAcupuntureforPhysicians" => "Certification in Medical Acupunture for Physicians",
						"CertifiedAlcoholandDrugAbuseCounselorMassachusettsBoardofSubstanceAbuseCounselorCertification" => "Certified Alcohol and Drug Abuse Counselor, Massachusetts Board of Substance Abuse, Counselor Certification 555",
						"CertifiedDiabetesEducator" => "Certified Diabetes Educator",
						"CertifiedGroupPsychotherapist-AmericanGroupPsychotherapyAssociation" => "Certified Group Psychotherapist - American Group Psychotherapy Association",
						"CertifiedinAdultWeightManagement" => "Certified in Adult Weight Management",
						"CertifiedinMarriage&FamilyTherapy" => "Certified in Marriage & Family Therapy",
						"CertifiedNurseMidwife" => "Certified Nurse Midwife",
						"CertifiedNutritianSupportClinician" => "Certified Nutritian Support Clinician",
						"CertifiedNutritionSupportDietitian" => "Certified Nutrition Support Dietitian",
						"CertifiedSpecialistinOncology" => "Certified Specialist in Oncology",
						"CertifiedSpecialistinPediatricNutrition" => "Certified Specialist in Pediatric Nutrition",
						"ClinicalPharmacology" => "Clinical Pharmacology",
						"ClinicalPsychologist" => "Clinical Psychologist",
						"CollegeofOsteopathicMedicine" => "College of Osteopathic Medicine",
						"ColonandRectalSurgery" => "Colon and Rectal Surgery",
						"CriticalCare" => "Critical Care",
						"Cytopathology" => "Cytopathology",
						"DermatologicPathology" => "Dermatologic Pathology",
						"Dermatopathology" => "Dermatopathology",
						"Developmental-BehavioralPediatrics" => "Developmental-Behavioral Pediatrics",
						"DiabetesUK" => "Diabetes UK",
						"DipUrology" => "Dip Urology",
						"Diplomat-AdultComprehensiveEchocardiographyNationalBoardofEchocardiography" => "Diplomat - Adult Comprehensive Echocardiography, National Board, of Echocardiography",
						"Diplomat-AmericanBoardofRadiology" => "Diplomat - American Board of Radiology",
						"Diplomat-CardiovascularDiseaseAmericanBoardofInternalMedicine" => "Diplomat - Cardiovascular Disease, American Board of Internal Medicine",
						"Diplomat-InternalMedicineAmericanBoardofInternalMedicine" => "Diplomat - Internal Medicine, American Board of Internal Medicine",
						"DiplomatAmericanBoardofRadiology" => "Diplomat American Board of Radiology",
						"DiplomatAmericanBoardofFamilyMedicine" => "Diplomat, American Board of Family Medicine",
						"Diplomate-AmericanBoardofDermatology" => "Diplomate -  American Board of Dermatology",
						"Diplomate-AmericanBoardofClinicalNeuropsychology" => "Diplomate - American Board of Clinical Neuropsychology",
						"Diplomate-AmericanBoardofPathology" => "Diplomate - American Board of Pathology",
						"Diplomate-AmericanBoardofPediatrics" => "Diplomate - American Board of Pediatrics",
						"Diplomate-AmericanBoardofSurgery" => "Diplomate - American Board of Surgery",
						"Diplomate-PediatricGastroenterologyAmericanBoardofPediatrics" => "Diplomate -Pediatric Gastroenterology, American Board of Pediatrics",
						"DiplomateofAmericanBoardofPsychiatryandNeurology" => "Diplomate of American Board of Psychiatry and Neurology",
						"DiplomateoftheAmericanBoardofGeriatrics" => "Diplomate of the American Board of Geriatrics",
						"DiplomateoftheAmericanBoardofInternalMedicine" => "Diplomate of the American Board of Internal Medicine",
						"DiplomateoftheAmericanBoardofInternalMedicineinEndocrinologyDiabetesandMetabolism" => "Diplomate of the American Board of Internal Medicine in Endocrinology, Diabetes and Metabolism",
						"DiplomateoftheAmericanBoardofInternalMedicineinInternalMedicine" => "Diplomate of the American Board of Internal Medicine in Internal Medicine",
						"DiplomateoftheAmericanBoardofPsychiatryandNeurology" => "Diplomate of the American Board of Psychiatry and Neurology",
						"DiplomateAmericanBoardofFamilyMedicine" => "Diplomate, American Board of Family Medicine",
						"DiplomateAmericanBoardofFamilyPractice" => "Diplomate, American Board of Family Practice",
						"DiplomateAmericanBoardofInternalMedicine" => "Diplomate, American Board of Internal Medicine",
						"DiplomateAmericanBoardofPsychiatryandNeurology" => "Diplomate, American Board of Psychiatry and Neurology",
						"DiplomateAmericanBoardofRadiology(DABR)" => "Diplomate, American Board of Radiology (DABR)",
						"DiplomateFederatedLicensingExaminationsBoard" => "Diplomate, Federated Licensing Examinations Board",
						"DiplomateNationalBoardofMedicalExaminers" => "Diplomate, National Board of Medical Examiners",
						"DiplomateNationalBoardInternalMedicineNationalBoardofExaminationsNewDelhiIndia" => "Diplomate, National Board, Internal Medicine, National Board of Examinations, New Delhi, India",
						"EducationalCommissionforForeignMedicalGraduates" => "Educational Commission for Foreign Medical Graduates",
						"EgyptianBoardOfUrology" => "Egyptian Board Of Urology",
						"EuropeanBoardofUrology" => "European Board of Urology",
						"FacharztfurDiagnostischeRadiologieAEKNOGermany" => "Facharzt fur Diagnostische Radiologie, AEKNO, Germany",
						"FamilyNursePractitioner" => "Family Nurse Practitioner",
						"FamilyPractice" => "Family Practice",
						"FellowofAmericanCollegeofSurgeons" => "Fellow of American College of Surgeons",
						"FellowofTheAmericanCongressofObstetriciansandGynecologists" => "Fellow of The American Congress of Obstetricians and Gynecologists",
						"FellowshipoftheRoyalCollegeofSurgeons" => "Fellowship of the Royal College of Surgeons",
						"GeneralMedicalCouncil(GMC)UK" => "General Medical Council (GMC), UK",
						"GeneralPsychiatry" => "General Psychiatry",
						"GeneralSurgery" => "General Surgery",
						"Genetics" => "Genetics",
						"GeorgiaStateMedicalBoard" => "Georgia State Medical Board",
						"GerontologicalSocietyofAmerica" => "Gerontological Society of America",
						"HematologyOncology" => "Hematology Oncology",
						"Hematopathology" => "Hematopathology",
						"InternationalAssociationofPancreatology" => "International Association of Pancreatology",
						"InternationalSociety-ClinicalDensitometry" => "International Society - Clinical Densitometry",
						"InternationalSocietyfortheStudyofVulvovaginalDisease" => "International Society for the Study of Vulvovaginal Disease",
						"JapaneseBoardofCardiovascularSurgery" => "Japanese Board of Cardiovascular Surgery",
						"JapaneseBoardofSurgery" => "Japanese Board of Surgery",
						"JointCouncilforApprovalofAdvancedTraininginHeadandNeckOncologicSurgery" => "Joint Council for Approval of Advanced Training in Head and Neck Oncologic Surgery",
						"LicensedClinicalPsychologistinArkansas" => "Licensed Clinical Psychologist in Arkansas",
						"LicensedClinicalSocialWorker" => "Licensed Clinical Social Worker",
						"LicensedMarriageandFamilyTherapistMassachusettsRegistration322" => "Licensed Marriage and Family Therapist, Massachusetts Registration 322",
						"LicensedPsychologist" => "Licensed Psychologist",
						"LicensedPsychologistArkansasRegistration#01-8P" => "Licensed Psychologist, Arkansas Registration # 01-8P",
						"LicensedPsychologistArkansasRegistration94-16PMassachusettsRegistration4879" => "Licensed Psychologist, Arkansas Registration 94-16P, Massachusetts Registration 4879",
						"LicensedPsychologistArkansasRegistration95-9P" => "Licensed Psychologist, Arkansas Registration 95-9P",
						"LouisianaStateBoardofMedicalExaminers" => "Louisiana State Board of Medical Examiners",
						"Magneticresonancecholangiopancreatography" => "Magnetic resonance cholangiopancreatography",
						"MasterLicenseAddictionCounselor" => "Master License Addiction Counselor",
						"Maternal-FetalMedicine" => "Maternal-Fetal Medicine",
						"MedicalCouncilofIndia" => "Medical Council of India",
						"MedicalLicensuretopracticeinPathology(Ukraine)" => "Medical Licensure to practice in Pathology (Ukraine)",
						"MedicalLicensuretopracticeinPediatrics(Ukraine)" => "Medical Licensure to practice in Pediatrics (Ukraine)",
						"MedicalMicrobiology" => "Medical Microbiology",
						"MedizininischeInformatikAEKNOGermany" => "Medizininische Informatik, AEKNO, Germany",
						"MexicanBoardofGastroenterology" => "Mexican Board of Gastroenterology",
						"MexicanBoardofGeneralSurgery" => "Mexican Board of General Surgery",
						"MexicanBoardofInternalMedicine" => "Mexican Board of Internal Medicine",
						"Mid-AmericaInterventionalRadiologicalSociety" => "Mid-America Interventional Radiological Society",
						"MRCPathHematology" => "MRCPath Hematology",
						"MRCS-EnglishEgytianBoardUrology" => "MRCS - English, Egytian Board Urology",
						"NationalAthleticTrainersAssociation" => "National Athletic Trainer's Association",
						"NationalBoardofEchocardiographyCertificate" => "National Board of Echocardiography Certificate",
						"NationalBoardofMedicalExaminers" => "National Board of Medical Examiners",
						"NationalCertificationCorporation-InpatientObstetrics" => "National Certification Corporation - Inpatient Obstetrics",
						"NationalCertificationCorporation-WomensHealthNursePractioner" => "National Certification Corporation - Women's Health Nurse Practioner",
						"NationalInstituteofHealth" => "National Institute of Health",
						"NationalInstituteofMedicalSciencesandNutritionMedicalAssociation" => "National Institute of Medical Sciences and Nutrition “Salvador Zubiran” Medical Association",
						"NationalMedicalAssociation" => "National Medical Association",
						"NeonatalResuscitationProgram" => "Neonatal Resuscitation Program",
						"Neonatal-PerinatalMedicine" => "Neonatal-Perinatal Medicine",
						"NorthAmericanMenopauseSociety" => "North American Menopause Society",
						"NuclearCardiology" => "Nuclear Cardiology",
						"NuclearMedicine" => "Nuclear Medicine",
						"NuclearRadiology" => "Nuclear Radiology",
						"OncologyNutrition" => "Oncology Nutrition",
						"PediatricAdvancedCardiacLifeSupport-AmericanHeartAssociation" => "Pediatric Advanced Cardiac Life Support - American Heart Association",
						"PediatricCardiology" => "Pediatric Cardiology",
						"PediatricCriticalCareMedicine" => "Pediatric Critical Care Medicine",
						"PediatricEmergencyMedicine" => "Pediatric Emergency Medicine",
						"PediatricEndocrinology" => "Pediatric Endocrinology",
						"PediatricGastroenterology" => "Pediatric Gastroenterology",
						"PediatricInfectiousDiseases" => "Pediatric Infectious Diseases",
						"PediatricPathology" => "Pediatric Pathology",
						"PediatricPsychology" => "Pediatric Psychology",
						"PediatricPulmonology" => "Pediatric Pulmonology",
						"PediatricRheumatology" => "Pediatric Rheumatology",
						"PediatricSurgery" => "Pediatric Surgery",
						"PediatricTransplantHepatology" => "Pediatric Transplant Hepatology",
						"Psychologist" => "Psychologist",
						"PsychosomaticMedicine" => "Psychosomatic Medicine",
						"PulaskiCountyMedicalSociety" => "Pulaski County Medical Society",
						"QualityAssuranceandUtilizationReview" => "Quality Assurance and Utilization Review",
						"ReedM.NesbitUrologicalSociety" => "Reed M. Nesbit Urological Society",
						"RegisteredDietitian" => "Registered Dietitian",
						"RhodeIslandBoardofMedicalLicensureandDiscipline" => "Rhode Island Board of Medical Licensure and Discipline",
						"RoyalAustralasianCollegeofPhysicians" => "Royal Australasian College of Physicians",
						"RoyalAustralasianCollegeofSurgeons" => "Royal Australasian College of Surgeons",
						"RoyalCollegeofPhysiciansofLondon" => "Royal College of Physicians of London",
						"RoyalCollegeofSurgeons" => "Royal College of Surgeons",
						"SleepResearchSociety" => "Sleep Research Society",
						"SocietyforClinicalVascularSurgery" => "Society for Clinical Vascular Surgery",
						"SocietyforVascularSurgery" => "Society for Vascular Surgery",
						"SocietyofBehavioralSleepMedicine" => "Society of Behavioral Sleep Medicine",
						"SocietyofEndocrinology" => "Society of Endocrinology",
						"SocietyofGovernmentServiceUrologists" => "Society of Government Service Urologists",
						"SocietyofInterventionalRadiology" => "Society of Interventional Radiology",
						"SocietyofSurgicalOncology" => "Society of Surgical Oncology",
						"SouthCarolinaBoardofMedicalExaminers" => "South Carolina Board of Medical Examiners",
						"SouthernAssociationforVascularSurgery" => "Southern Association for Vascular Surgery",
						"SouthwesternOncologyGroup" => "Southwestern Oncology Group",
						"SpinalCordMedicine" => "Spinal Cord Medicine",
						"StudentNationalMedicalAssociation" => "Student National Medical Association",
						"TheEndocrineSociety" => "The Endocrine Society",
						"TheTamilnaduMedicalCouncil" => "The Tamilnadu Medical Council",
						"TherapeuticRadiology" => "Therapeutic Radiology",
						"TransesophagealEchocardiography" => "Transesophageal Echocardiography",
						"UnitedCouncilforNeurologicSubspecialties(BehavioralNeurology&Neuropsychiatry)" => "United Council for Neurologic Subspecialties (Behavioral Neurology & Neuropsychiatry)",
						"UniversityofWestIndiesKingstonJamaicaDA" => "University of West Indies, Kingston, Jamaica, DA",
						"Urology" => "Urology",
						"Vascular&InterventionalRadiology" => "Vascular & Interventional Radiology",
						"VascularandEndovascularSurgicalSociety" => "Vascular and Endovascular Surgical Society",
						"VascularNeurologyAmericanBoardofPsychiatryandNeurology" => "Vascular Neurology, American Board of Psychiatry and Neurology",
						"VascularSurgery" => "Vascular Surgery",
						"VestibularandRelatedDisordersAssociation" => "Vestibular and Related Disorders Association",
						"WestAfricanCollegeofSurgeons-DiagnosticRadiology" => "West African College of Surgeons - Diagnostic Radiology",
						"WomensHealthNursePractitioner" => "Women's Health Nurse Practitioner",
	                ),
	            ),
        	),
        ),
         
        array (
          'id' => 'person_research_profiles_link',
          'type' => 'url',
          'name' => 'Profiles Link',
          'tab' => 'tab_edu',
        ),
         
        array (
          'id' => 'person_pubmed_author_id',
          'type' => 'text',
          'name' => 'Pubmed Author ID',
          'tab' => 'tab_edu',
        ),
         
        array (
          'id' => 'pubmed_author_number',
          'name' => 'Number Lastest Articles',
          'type' => 'select',
          'placeholder' => 'Select an Item',
          'tab' => 'tab_edu',
        ),
         
        array (
          'id' => 'person_research_bio',
          'name' => 'Researcher Bio',
          'type' => 'wysiwyg',
          'tab' => 'tab_research',
        ),
         
        array (
          'id' => 'person_research_interests',
          'type' => 'textarea',
          'name' => 'Research Interests',
          'tab' => 'tab_research',
        ),

        array(
          	'id'     => 'person_awards',
          	'type'   => 'group',
          	'tab' => 'tab_extra',
	      	'clone'  => true,
	      	'sort_clone' => true,
	      	'fields' => array(
	            array(
	                'name' => 'Year',
	                'id'   => 'award_year',
	                'type' => 'text',
	            ),
	            array(
	                'name' => 'Award Title',
	                'id'   => 'award_title',
	                'type' => 'text',
	            ),
	            array(
	                'name'    => 'Information',
	                'id'      => 'award_infor',
	                'type'    => 'wysiwyg',
	            ),
        	),
        ),
         
        array (
          'id' => 'person_additional_info',
          'name' => 'Additional Info',
          'type' => 'wysiwyg',
          'tab' => 'tab_extra',
        ),
      ),
  // //     'validation' => array(
		// //     'rules'  => array(
		// //         'location_address_1' => array(
		// //             'required'  => true,
		// //         ),
		// //         'location_city' => array(
		// //             'required'  => true,
		// //         ),
		// //         'location_state' => array(
		// //             'required'  => true,
		// //         ),
		// //         'location_zip' => array(
		// //             'required'  => true,
		// //             'zipcodeUS' => true,
		// //             'maxlength' => 10,
  // //         			'minlength' => 5,
		// //         ),
		// //         'location_map' => array(
		// //             'required'  => true,
		// //         ),
		// //         'location_phone' => array(
		// //             'required'  => true,
		// //             'phoneUS' => true,
		// //         ),
		// //     ),
		// //     // Optional override of default error messages
		// //     // 'messages' => array(
		// //     //     'field_id' => array(
		// //     //         'required'  => 'Password is required',
		// //     //         'minlength' => 'Password must be at least 7 characters',
		// //     //     ),
		// //     // )
		// // ),
    );


    return $meta_boxes;

}